// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionAPI.Models;

#nullable disable

namespace TransactionAPI.Migrations
{
    [DbContext(typeof(TransactionDetailContext))]
    partial class TransactionDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionAPI.Models.TransactionDetail", b =>
                {
                    b.Property<int>("TransactionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionDetailId"));

                    b.Property<long>("ALLOC_TXN_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("CONV_DEED_ABBREVIATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CONV_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DEED_INO")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("DEED_OWNER_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DEED_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DEED_TYPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LOG_CREATED_TS")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("LOT_NO")
                        .HasColumnType("int");

                    b.Property<string>("PRINT_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SOURCE_REF_ABBREVIATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionDetailId");

                    b.ToTable("TransactionDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
